pyside6-rcc pynotebook.qrc -o pynotebook_rc.py
pyside6-uic pynotebookwindow.ui -o ui_pynotebookwindow.py
pyside6-uic RichTextEdit.ui -o ui_RichTextEdit.py
pyside6-uic style_dlg.ui -o ui_style_dlg.py
pyside6-uic select_style_dlg.ui -o ui_select_style_dlg.py
pyside6-uic title_label_widget.ui -o ui_title_label_widget.py
pyside6-uic favorites_widget.ui -o ui_favorites_widget.py
pyside6-uic page_info_dlg.ui -o ui_page_info_dlg.py
pyside6-uic prefs_dialog.ui -o ui_prefs_dialog.py
pyside6-uic about_dialog.ui -o ui_about_dialog.py
pyside6-uic favorites_dialog.ui -o ui_favorites_dialog.py
pyside6-uic search_dialog.ui -o ui_search_dialog.py
pyside6-uic table_format_dlg.ui -o ui_table_format_dlg.py
pyside6-uic choose_page_to_link_dlg.ui -o ui_choose_page_to_link_dlg.py
pyside6-uic add_web_link_dlg.ui -o ui_add_web_link_dlg.py
