# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pynotebookwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDockWidget, QHBoxLayout, QHeaderView,
    QLabel, QLineEdit, QListWidgetItem, QMainWindow,
    QMenu, QMenuBar, QPushButton, QSizePolicy,
    QStackedWidget, QStatusBar, QTabWidget, QToolBar,
    QTreeWidgetItem, QVBoxLayout, QWidget)

from date_tree import CDateTree
from favorites_widget import CFavoritesWidget
from page_history_widget import CPageHistoryWidget
from page_title_list import CPageTitleList
from page_tree import CPageTree
from search_widget import CSearchWidget
from tag_list import CTagList
from title_label_widget import CTitleLabelWidget
import pynotebook_rc

class Ui_NoteBookClass(object):
    def setupUi(self, PyNoteBookWindow):
        if not PyNoteBookWindow.objectName():
            PyNoteBookWindow.setObjectName(u"PyNoteBookWindow")
        PyNoteBookWindow.resize(855, 768)
        icon = QIcon()
        icon.addFile(u":/NoteBook/NoteBook.ico", QSize(), QIcon.Normal, QIcon.Off)
        PyNoteBookWindow.setWindowIcon(icon)
        self.actionExit = QAction(PyNoteBookWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionCut = QAction(PyNoteBookWindow)
        self.actionCut.setObjectName(u"actionCut")
        self.actionCopy = QAction(PyNoteBookWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionPaste = QAction(PyNoteBookWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        self.actionAbout_NoteBook = QAction(PyNoteBookWindow)
        self.actionAbout_NoteBook.setObjectName(u"actionAbout_NoteBook")
        self.actionNew_Toolbar = QAction(PyNoteBookWindow)
        self.actionNew_Toolbar.setObjectName(u"actionNew_Toolbar")
        self.actionAdd_Page_to_Favorites = QAction(PyNoteBookWindow)
        self.actionAdd_Page_to_Favorites.setObjectName(u"actionAdd_Page_to_Favorites")
        self.actionSettings = QAction(PyNoteBookWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        self.actionNew_Notebook = QAction(PyNoteBookWindow)
        self.actionNew_Notebook.setObjectName(u"actionNew_Notebook")
        self.actionOpen_Notebook = QAction(PyNoteBookWindow)
        self.actionOpen_Notebook.setObjectName(u"actionOpen_Notebook")
        self.actionClose = QAction(PyNoteBookWindow)
        self.actionClose.setObjectName(u"actionClose")
        self.actionNew_Page = QAction(PyNoteBookWindow)
        self.actionNew_Page.setObjectName(u"actionNew_Page")
        self.actionImport_TiddlyWiki = QAction(PyNoteBookWindow)
        self.actionImport_TiddlyWiki.setObjectName(u"actionImport_TiddlyWiki")
        self.actionPage_Info = QAction(PyNoteBookWindow)
        self.actionPage_Info.setObjectName(u"actionPage_Info")
        self.actionRecent_Notebooks = QAction(PyNoteBookWindow)
        self.actionRecent_Notebooks.setObjectName(u"actionRecent_Notebooks")
        self.actionNew_Folder = QAction(PyNoteBookWindow)
        self.actionNew_Folder.setObjectName(u"actionNew_Folder")
        self.actionNew_Top_Level_Page = QAction(PyNoteBookWindow)
        self.actionNew_Top_Level_Page.setObjectName(u"actionNew_Top_Level_Page")
        self.actionNew_Top_Level_Folder = QAction(PyNoteBookWindow)
        self.actionNew_Top_Level_Folder.setObjectName(u"actionNew_Top_Level_Folder")
        self.actionAbout_Qt = QAction(PyNoteBookWindow)
        self.actionAbout_Qt.setObjectName(u"actionAbout_Qt")
        self.actionExport = QAction(PyNoteBookWindow)
        self.actionExport.setObjectName(u"actionExport")
        self.actionImportPage = QAction(PyNoteBookWindow)
        self.actionImportPage.setObjectName(u"actionImportPage")
        self.actionNew_To_Do_List = QAction(PyNoteBookWindow)
        self.actionNew_To_Do_List.setObjectName(u"actionNew_To_Do_List")
        self.centralWidget = QWidget(PyNoteBookWindow)
        self.centralWidget.setObjectName(u"centralWidget")
        self.verticalLayout = QVBoxLayout(self.centralWidget)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.titleLabelWidget = CTitleLabelWidget(self.centralWidget)
        self.titleLabelWidget.setObjectName(u"titleLabelWidget")

        self.verticalLayout.addWidget(self.titleLabelWidget)

        self.editorStackedWidget = QStackedWidget(self.centralWidget)
        self.editorStackedWidget.setObjectName(u"editorStackedWidget")
        self.editorStackedWidget.setSizeIncrement(QSize(0, 1))

        self.verticalLayout.addWidget(self.editorStackedWidget)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label_5 = QLabel(self.centralWidget)
        self.label_5.setObjectName(u"label_5")

        self.horizontalLayout.addWidget(self.label_5)

        self.tagsEdit = QLineEdit(self.centralWidget)
        self.tagsEdit.setObjectName(u"tagsEdit")

        self.horizontalLayout.addWidget(self.tagsEdit)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.messageLabel = QLabel(self.centralWidget)
        self.messageLabel.setObjectName(u"messageLabel")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messageLabel.sizePolicy().hasHeightForWidth())
        self.messageLabel.setSizePolicy(sizePolicy)

        self.horizontalLayout_2.addWidget(self.messageLabel)

        self.savePageButton = QPushButton(self.centralWidget)
        self.savePageButton.setObjectName(u"savePageButton")

        self.horizontalLayout_2.addWidget(self.savePageButton)


        self.verticalLayout.addLayout(self.horizontalLayout_2)

        PyNoteBookWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QMenuBar(PyNoteBookWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 855, 21))
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuImport = QMenu(self.menuFile)
        self.menuImport.setObjectName(u"menuImport")
        self.menuEdit = QMenu(self.menuBar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuSettings = QMenu(self.menuBar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuFavorites = QMenu(self.menuBar)
        self.menuFavorites.setObjectName(u"menuFavorites")
        self.menuToolbars = QMenu(self.menuBar)
        self.menuToolbars.setObjectName(u"menuToolbars")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuPage = QMenu(self.menuBar)
        self.menuPage.setObjectName(u"menuPage")
        PyNoteBookWindow.setMenuBar(self.menuBar)
        self.statusBar = QStatusBar(PyNoteBookWindow)
        self.statusBar.setObjectName(u"statusBar")
        PyNoteBookWindow.setStatusBar(self.statusBar)
        self.navigationDockWidget = QDockWidget(PyNoteBookWindow)
        self.navigationDockWidget.setObjectName(u"navigationDockWidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.navigationDockWidget.sizePolicy().hasHeightForWidth())
        self.navigationDockWidget.setSizePolicy(sizePolicy1)
        self.navigationDockWidget.setMinimumSize(QSize(280, 144))
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.verticalLayout_3 = QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.navigationTabWidget = QTabWidget(self.dockWidgetContents)
        self.navigationTabWidget.setObjectName(u"navigationTabWidget")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(1)
        sizePolicy2.setHeightForWidth(self.navigationTabWidget.sizePolicy().hasHeightForWidth())
        self.navigationTabWidget.setSizePolicy(sizePolicy2)
        self.treeTab = QWidget()
        self.treeTab.setObjectName(u"treeTab")
        self.verticalLayout_4 = QVBoxLayout(self.treeTab)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.pageTree = CPageTree(self.treeTab)
        self.pageTree.setObjectName(u"pageTree")

        self.verticalLayout_4.addWidget(self.pageTree)

        self.navigationTabWidget.addTab(self.treeTab, "")
        self.listTab = QWidget()
        self.listTab.setObjectName(u"listTab")
        self.verticalLayout_5 = QVBoxLayout(self.listTab)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.pageTitleList = CPageTitleList(self.listTab)
        self.pageTitleList.setObjectName(u"pageTitleList")
        self.pageTitleList.setSortingEnabled(True)

        self.verticalLayout_5.addWidget(self.pageTitleList)

        self.navigationTabWidget.addTab(self.listTab, "")
        self.dateTab = QWidget()
        self.dateTab.setObjectName(u"dateTab")
        self.verticalLayout_6 = QVBoxLayout(self.dateTab)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.dateTree = CDateTree(self.dateTab)
        self.dateTree.setObjectName(u"dateTree")
        self.dateTree.setSortingEnabled(False)

        self.verticalLayout_6.addWidget(self.dateTree)

        self.navigationTabWidget.addTab(self.dateTab, "")
        self.tagsTab = QWidget()
        self.tagsTab.setObjectName(u"tagsTab")
        self.verticalLayout_7 = QVBoxLayout(self.tagsTab)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.tagList = CTagList(self.tagsTab)
        self.tagList.setObjectName(u"tagList")
        self.tagList.setSortingEnabled(True)

        self.verticalLayout_7.addWidget(self.tagList)

        self.navigationTabWidget.addTab(self.tagsTab, "")

        self.verticalLayout_3.addWidget(self.navigationTabWidget)

        self.navigationDockWidget.setWidget(self.dockWidgetContents)
        PyNoteBookWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.navigationDockWidget)
        self.recentlyViewedDockWidget = QDockWidget(PyNoteBookWindow)
        self.recentlyViewedDockWidget.setObjectName(u"recentlyViewedDockWidget")
        self.recentlyViewedDockWidget.setMinimumSize(QSize(294, 146))
        self.dockWidgetContents_3 = QWidget()
        self.dockWidgetContents_3.setObjectName(u"dockWidgetContents_3")
        self.verticalLayout_2 = QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.auxNavigationTabWidget = QTabWidget(self.dockWidgetContents_3)
        self.auxNavigationTabWidget.setObjectName(u"auxNavigationTabWidget")
        self.auxNavigationTabWidget.setMinimumSize(QSize(0, 0))
        self.auxNavigationTabWidget.setTabPosition(QTabWidget.South)
        self.pageHistoryTab = QWidget()
        self.pageHistoryTab.setObjectName(u"pageHistoryTab")
        self.verticalLayout_8 = QVBoxLayout(self.pageHistoryTab)
        self.verticalLayout_8.setSpacing(1)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(1, 1, 1, 1)
        self.recentlyViewedList = CPageHistoryWidget(self.pageHistoryTab)
        self.recentlyViewedList.setObjectName(u"recentlyViewedList")

        self.verticalLayout_8.addWidget(self.recentlyViewedList)

        self.auxNavigationTabWidget.addTab(self.pageHistoryTab, "")
        self.searchTab = QWidget()
        self.searchTab.setObjectName(u"searchTab")
        self.verticalLayout_9 = QVBoxLayout(self.searchTab)
        self.verticalLayout_9.setSpacing(1)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(1, 1, 1, 1)
        self.searchWidget = CSearchWidget(self.searchTab)
        self.searchWidget.setObjectName(u"searchWidget")

        self.verticalLayout_9.addWidget(self.searchWidget)

        self.auxNavigationTabWidget.addTab(self.searchTab, "")
        self.favoritesTab = QWidget()
        self.favoritesTab.setObjectName(u"favoritesTab")
        self.verticalLayout_10 = QVBoxLayout(self.favoritesTab)
        self.verticalLayout_10.setSpacing(1)
        self.verticalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(1, 1, 1, 1)
        self.favoritesWidget = CFavoritesWidget(self.favoritesTab)
        self.favoritesWidget.setObjectName(u"favoritesWidget")

        self.verticalLayout_10.addWidget(self.favoritesWidget)

        self.auxNavigationTabWidget.addTab(self.favoritesTab, "")

        self.verticalLayout_2.addWidget(self.auxNavigationTabWidget)

        self.recentlyViewedDockWidget.setWidget(self.dockWidgetContents_3)
        PyNoteBookWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.recentlyViewedDockWidget)
        self.toolBar = QToolBar(PyNoteBookWindow)
        self.toolBar.setObjectName(u"toolBar")
        PyNoteBookWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuPage.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuFavorites.menuAction())
        self.menuBar.addAction(self.menuToolbars.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew_Notebook)
        self.menuFile.addAction(self.actionOpen_Notebook)
        self.menuFile.addAction(self.actionRecent_Notebooks)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuImport.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuImport.addAction(self.actionImportPage)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuSettings.addAction(self.actionSettings)
        self.menuFavorites.addAction(self.actionAdd_Page_to_Favorites)
        self.menuToolbars.addAction(self.actionNew_Toolbar)
        self.menuHelp.addAction(self.actionAbout_NoteBook)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuPage.addAction(self.actionNew_Page)
        self.menuPage.addSeparator()
        self.menuPage.addAction(self.actionPage_Info)
        self.toolBar.addAction(self.actionNew_Page)
        self.toolBar.addAction(self.actionNew_To_Do_List)
        self.toolBar.addAction(self.actionNew_Top_Level_Page)
        self.toolBar.addAction(self.actionNew_Folder)
        self.toolBar.addAction(self.actionNew_Top_Level_Folder)

        self.retranslateUi(PyNoteBookWindow)
        self.actionExit.triggered.connect(PyNoteBookWindow.close)

        self.editorStackedWidget.setCurrentIndex(-1)
        self.navigationTabWidget.setCurrentIndex(3)
        self.auxNavigationTabWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(PyNoteBookWindow)
    # setupUi

    def retranslateUi(self, PyNoteBookWindow):
        PyNoteBookWindow.setWindowTitle(QCoreApplication.translate("NoteBookClass", u"NoteBook", None))
        self.actionExit.setText(QCoreApplication.translate("NoteBookClass", u"Exit", None))
        self.actionCut.setText(QCoreApplication.translate("NoteBookClass", u"Cut", None))
        self.actionCopy.setText(QCoreApplication.translate("NoteBookClass", u"Copy", None))
        self.actionPaste.setText(QCoreApplication.translate("NoteBookClass", u"Paste", None))
        self.actionAbout_NoteBook.setText(QCoreApplication.translate("NoteBookClass", u"About NoteBook...", None))
        self.actionNew_Toolbar.setText(QCoreApplication.translate("NoteBookClass", u"New Toolbar...", None))
        self.actionAdd_Page_to_Favorites.setText(QCoreApplication.translate("NoteBookClass", u"Add Page to Favorites", None))
        self.actionSettings.setText(QCoreApplication.translate("NoteBookClass", u"Settings...", None))
        self.actionNew_Notebook.setText(QCoreApplication.translate("NoteBookClass", u"New Notebook...", None))
        self.actionOpen_Notebook.setText(QCoreApplication.translate("NoteBookClass", u"Open Noteboook...", None))
        self.actionClose.setText(QCoreApplication.translate("NoteBookClass", u"Close", None))
        self.actionNew_Page.setText(QCoreApplication.translate("NoteBookClass", u"New Page", None))
        self.actionImport_TiddlyWiki.setText(QCoreApplication.translate("NoteBookClass", u"Import TiddlyWiki...", None))
        self.actionPage_Info.setText(QCoreApplication.translate("NoteBookClass", u"Page Info...", None))
        self.actionRecent_Notebooks.setText(QCoreApplication.translate("NoteBookClass", u"Recent Notebooks", None))
        self.actionNew_Folder.setText(QCoreApplication.translate("NoteBookClass", u"New Folder", None))
        self.actionNew_Top_Level_Page.setText(QCoreApplication.translate("NoteBookClass", u"New Top-Level Page", None))
        self.actionNew_Top_Level_Folder.setText(QCoreApplication.translate("NoteBookClass", u"New Top-Level Folder", None))
        self.actionAbout_Qt.setText(QCoreApplication.translate("NoteBookClass", u"About Qt...", None))
        self.actionExport.setText(QCoreApplication.translate("NoteBookClass", u"Export...", None))
        self.actionImportPage.setText(QCoreApplication.translate("NoteBookClass", u"Page...", None))
        self.actionNew_To_Do_List.setText(QCoreApplication.translate("NoteBookClass", u"New To Do List", None))
#if QT_CONFIG(tooltip)
        self.actionNew_To_Do_List.setToolTip(QCoreApplication.translate("NoteBookClass", u"Create a new To Do list", None))
#endif // QT_CONFIG(tooltip)
        self.label_5.setText(QCoreApplication.translate("NoteBookClass", u"Tags", None))
        self.messageLabel.setText("")
#if QT_CONFIG(tooltip)
        self.savePageButton.setToolTip(QCoreApplication.translate("NoteBookClass", u"Save Page (Ctrl+S)", None))
#endif // QT_CONFIG(tooltip)
        self.savePageButton.setText(QCoreApplication.translate("NoteBookClass", u"Save Page", None))
#if QT_CONFIG(shortcut)
        self.savePageButton.setShortcut(QCoreApplication.translate("NoteBookClass", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.menuFile.setTitle(QCoreApplication.translate("NoteBookClass", u"File", None))
        self.menuImport.setTitle(QCoreApplication.translate("NoteBookClass", u"Import...", None))
        self.menuEdit.setTitle(QCoreApplication.translate("NoteBookClass", u"Edit", None))
        self.menuSettings.setTitle(QCoreApplication.translate("NoteBookClass", u"Settings", None))
        self.menuFavorites.setTitle(QCoreApplication.translate("NoteBookClass", u"Favorites", None))
        self.menuToolbars.setTitle(QCoreApplication.translate("NoteBookClass", u"Toolbars", None))
        self.menuHelp.setTitle(QCoreApplication.translate("NoteBookClass", u"Help", None))
        self.menuPage.setTitle(QCoreApplication.translate("NoteBookClass", u"Page", None))
        self.navigationDockWidget.setWindowTitle(QCoreApplication.translate("NoteBookClass", u"Navigation", None))
        ___qtreewidgetitem = self.pageTree.headerItem()
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("NoteBookClass", u"Page Title", None));
        self.navigationTabWidget.setTabText(self.navigationTabWidget.indexOf(self.treeTab), QCoreApplication.translate("NoteBookClass", u"Tree", None))
        self.navigationTabWidget.setTabText(self.navigationTabWidget.indexOf(self.listTab), QCoreApplication.translate("NoteBookClass", u"List", None))
        ___qtreewidgetitem1 = self.dateTree.headerItem()
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("NoteBookClass", u"Date", None));
        self.navigationTabWidget.setTabText(self.navigationTabWidget.indexOf(self.dateTab), QCoreApplication.translate("NoteBookClass", u"Date", None))
        self.navigationTabWidget.setTabText(self.navigationTabWidget.indexOf(self.tagsTab), QCoreApplication.translate("NoteBookClass", u"Tags", None))
        self.recentlyViewedDockWidget.setWindowTitle("")
        self.auxNavigationTabWidget.setTabText(self.auxNavigationTabWidget.indexOf(self.pageHistoryTab), QCoreApplication.translate("NoteBookClass", u"Recently Viewed", None))
        self.auxNavigationTabWidget.setTabText(self.auxNavigationTabWidget.indexOf(self.searchTab), QCoreApplication.translate("NoteBookClass", u"Search", None))
        self.auxNavigationTabWidget.setTabText(self.auxNavigationTabWidget.indexOf(self.favoritesTab), QCoreApplication.translate("NoteBookClass", u"Favorites", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("NoteBookClass", u"toolBar", None))
    # retranslateUi

